/** Shared Smart Gift Finder options + search keyword maps (moderngifts-style coverage). */

export const GIFT_FINDER_OCCASIONS = [
  { value: 'birthday', label: '🎂 Birthday' },
  { value: 'anniversary', label: '💍 Anniversary' },
  { value: 'wedding', label: '👰 Wedding' },
  { value: 'house-warming', label: '🏠 House Warming' },
  { value: 'farewell', label: '👋 Farewell' },
  { value: 'baby-shower', label: '👶 Baby Shower' },
  { value: 'valentine', label: "❤️ Valentine's Day" },
  { value: 'womens-day', label: "🌷 Women's Day" },
  { value: 'mothers-day', label: "🌸 Mother's Day" },
  { value: 'fathers-day', label: "👔 Father's Day" },
  { value: 'friendship', label: '🤝 Friendship Day' },
  { value: 'teachers-day', label: "📚 Teacher's Day" },
  { value: 'childrens-day', label: "🎈 Children's Day" },
  { value: 'new-year', label: '🎆 New Year' },
  { value: 'christmas', label: '🎄 Christmas' },
  { value: 'holi', label: '🎨 Holi' },
  { value: 'diwali', label: '🪔 Diwali' },
  { value: 'rakhi', label: '🧵 Rakhi' },
  { value: 'onam', label: '🌺 Onam' },
];

export const GIFT_FINDER_TYPES = [
  { value: 'personalized', label: '🖼️ Customized Gifts' },
  { value: 'frames', label: '🪞 Frames' },
  { value: 'unique-gifts', label: '✨ Unique Gifts' },
  { value: 'for-her', label: '💕 Gift for Her' },
  { value: 'for-him', label: '💙 Gift for Him' },
  { value: 'for-babies', label: '👶 Collections for Babies' },
  { value: 'anniversary-gifts', label: '💐 Anniversary Gifts' },
  { value: 'combos', label: '🎁 Combos' },
  { value: 'hampers', label: '🧺 Hampers' },
  { value: 'chocolates', label: '🍫 Chocolates' },
  { value: 'return-gifts', label: '↩️ Return Gifts' },
  { value: 'modern-special', label: '⭐ Modern Special' },
];

export const OCCASION_KEYWORDS = {
  birthday: ['birthday', 'bday'],
  anniversary: ['anniversary'],
  wedding: ['wedding', 'bridal', 'bride', 'groom'],
  'house-warming': ['house warming', 'housewarming', 'griha', 'new home'],
  farewell: ['farewell', 'goodbye', 'send-off', 'going away'],
  'baby-shower': ['baby shower', 'newborn', 'new mom'],
  valentine: ['valentine', 'valentines', 'love', 'romantic', 'couple'],
  'womens-day': ["women's day", 'womens day', 'woman', 'for her'],
  'mothers-day': ['mother', 'mom', 'mummy', 'mama', "mother's day"],
  'fathers-day': ['father', 'dad', 'papa', "father's day"],
  friendship: ['friend', 'friendship', 'bestie', 'bff'],
  'teachers-day': ['teacher', 'guru', "teacher's day"],
  'childrens-day': ['children', 'kids', "children's day"],
  'new-year': ['new year', 'newyear', 'nye'],
  christmas: ['christmas', 'xmas', 'santa'],
  holi: ['holi', 'festival of colours'],
  diwali: ['diwali', 'deepavali', 'festive', 'lamp'],
  rakhi: ['rakhi', 'raksha', 'sibling'],
  onam: ['onam', 'kerala'],
};

export const GIFT_TYPE_KEYWORDS = {
  personalized: ['personalized', 'customized', 'custom', 'name print'],
  frames: ['frame', 'photo frame', 'spotify frame', 'moon frame'],
  'unique-gifts': ['unique', 'unusual', 'creative', 'special gift'],
  'for-her': ['her', 'women', 'girl', 'wife', 'girlfriend', 'sister', 'mom'],
  'for-him': ['him', 'men', 'man', 'husband', 'boyfriend', 'brother', 'dad'],
  'for-babies': ['baby', 'infant', 'toddler', 'kids gift', 'newborn'],
  'anniversary-gifts': ['anniversary', 'years together', 'milestone'],
  combos: ['combo', 'gift set', 'gift pack', 'bundle'],
  hampers: ['hamper', 'bouquet', 'basket', 'gift box'],
  chocolates: ['chocolate', 'cocoa', 'sweet'],
  'return-gifts': ['return gift', 'party favor', 'favor'],
  'modern-special': ['modern', 'trending', 'premium', 'limited', 'exclusive'],
};
